import numpy as np
from tests import *
if __name__ == "__main__":
    np.random.seed(318)
    #plotssimd()
    #plotgaussian()
    #plotfouriernoise()
    #plotnoise()
    #downsamplingexperiment()
    #testquadraticparameterselection()
    #testnewestimator()
    #forPresentation()
    #plotparametermethods()
    #ploteigenvalues()
    #ploteigenvalues_()
    #plotprojections()
    plotprojectionparameter()
    #plotfouriernoise()
    #plotdownsampled()
    #testConvolution()
    #thedenoisingexperiment()
    #TVandQVexamples()
    #testparameterselection()
    #testquadratcic()
    #plotdownsampled()
    #deblurringexperiment()
    #QVTVdenoising()
